INSERT INTO users (id, username, name, surname, password, email, phone_number, role, active, balance, failed_attempts, lock_time, locked) VALUES (CAST(RANDOM_UUID() AS VARCHAR(36)), 'admin', 'Administrator', 'System', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6', 'admin@example.com', '+380501234567', 'ADMIN', TRUE, 0.00, 0, NULL, FALSE);
INSERT INTO users (id, username, name, surname, password, email, phone_number, role, active, balance, failed_attempts, lock_time, locked) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'manager', 'Manager', 'System', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6', 'manager@example.com', '+380661234567', 'MANAGER', TRUE, 0.00, 0, NULL, FALSE);
INSERT INTO users (id, username, name, surname, password, email, phone_number, role, active, balance, failed_attempts, lock_time, locked) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'user1', 'bot', 'bot', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6', 'user1@example.com', '+380731234567', 'USER', TRUE, 0.00, 0, NULL, FALSE);
INSERT INTO users (id, username, name, surname, password, email, phone_number, role, active, balance, failed_attempts, lock_time, locked) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'user2', 'bot', 'bot', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6', 'user2@example.com', '+380801234567', 'USER', TRUE, 0.00, 0, NULL, FALSE);
INSERT INTO users (id, username, name, surname, password, email, phone_number, role, active, balance, failed_attempts, lock_time, locked) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'support', 'bot', 'bot', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6', 'support@example.com', '+380911234567', 'USER', TRUE, 0.00, 0, NULL, FALSE);

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot, image_url) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Paris Escape', 'Romantic weekend getaway in the heart of Paris with exquisite cuisine', 1299.99, 'ADVENTURE', 'PLANE', 'FIVE_STARS', 'REGISTERED', DATEADD('DAY',2,CURRENT_DATE), DATEADD('DAY',9,CURRENT_DATE), (SELECT id FROM users WHERE username='admin'), TRUE, 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&h=675&crop=entropy&q=80');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Paris Escape'),'en', 'Paris Escape', 'Romantic weekend getaway in the heart of Paris with exquisite cuisine');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Paris Escape'),'uz', 'Parijga qochish', 'Parij markazida nafis oshxonali romantik dam olish');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Paris Escape'),'ru', 'Побег в Париж', 'Романтический уикенд в самом сердце Парижа с изысканной кухней');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Paris Escape'),'ka', 'პარიზის გაქცევა', 'რომანტიკული ვიკენდი პარიზის გულში დახვეწილი სამზარეულოთი');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot, image_url) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Tokyo Discovery', 'Immerse yourself in Tokyo`s vibrant urban culture and modern marvels', 899.50, 'CULTURAL', 'TRAIN', 'FOUR_STARS', 'PAID', CURRENT_DATE, DATEADD('DAY',5,CURRENT_DATE), (SELECT id FROM users WHERE username='user1'), FALSE, 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1200&h=675&crop=entropy&q=80');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Tokyo Discovery'),'en', 'Tokyo Discovery', 'Immerse yourself in Tokyo`s vibrant urban culture and modern marvels');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Tokyo Discovery'),'uz', 'Tokioni kashf etish', 'Tokioning jo''shqin shahar madaniyati va zamonaviy mo''jizalariga sho''ng''ing');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Tokyo Discovery'),'ru', 'Открытие Токио', 'Погрузитесь в яркую городскую культуру Токио и современные чудеса');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Tokyo Discovery'),'ka', 'ტოკიოს აღმოჩენა', 'ჩაეფლეთ ტოკიოს ცოცხალ ურბანულ კულტურაში და თანამედროვე საოცრებებში');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot, image_url) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'African Safari', 'Experience an unforgettable journey through the wild African savannah', 1599.75, 'SAFARI', 'PRIVATE_CAR', 'THREE_STARS', 'REGISTERED', DATEADD('DAY',5,CURRENT_DATE), DATEADD('DAY',15,CURRENT_DATE), (SELECT id FROM users WHERE username='manager'), TRUE, 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&h=675&crop=entropy&q=80');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='African Safari'),'en', 'African Safari', 'Experience an unforgettable journey through the wild African savannah');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='African Safari'),'uz', 'Afrika safari', 'Afrika savannasining yovvoyi tabiatida unutilmas sayohat');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='African Safari'),'ru', 'Африканское сафари', 'Незабываемое путешествие через дикую африканскую саванну');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='African Safari'),'ka', 'აფრიკული საფარი', 'დაუვიწყარი მოგზაურობა აფრიკის ველური სავანით');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot, image_url) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Eco Adventure', 'Sustainable eco-friendly tour with nature trails and minimal impact', 499.99, 'ECO', 'BUS', 'TWO_STARS', 'CANCELED', DATEADD('DAY',-1,CURRENT_DATE), DATEADD('DAY',3,CURRENT_DATE), (SELECT id FROM users WHERE username='support'), FALSE, 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&h=675&crop=entropy&q=80');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Eco Adventure'),'en', 'Eco Adventure', 'Sustainable eco-friendly tour with nature trails and minimal impact');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Eco Adventure'),'uz', 'Eko sarguzasht', 'Tabiat yo''llari va minimal ta''sirga ega ekologik tur');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Eco Adventure'),'ru', 'Эко-приключение', 'Экологичный тур с природными тропами и минимальным воздействием');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Eco Adventure'),'ka', 'ეკო თავგადასავალი', 'ეკოლოგიური ტური ბუნების ბილიკებით და მინიმალური ზემოქმედებით');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot, image_url) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Health Retreat', 'Relax at our health resort with rejuvenating treatments', 350.00, 'HEALTH', 'BUS', 'ONE_STAR', 'REGISTERED', DATEADD('DAY', 5,CURRENT_DATE), DATEADD('DAY',12,CURRENT_DATE), (SELECT id FROM users WHERE username='user1'), FALSE, 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&h=675&crop=entropy&q=80');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Health Retreat'),'en', 'Health Retreat', 'Relax at our health resort with rejuvenating treatments');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Health Retreat'),'uz', 'Sog''lomlashtirish dami', 'Sog''lomlashtirish kurortimizda tiklovchi muolajalar bilan hordiq oling');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Health Retreat'),'ru', 'Оздоровительный отдых', 'Расслабьтесь на нашем оздоровительном курорте с восстановительными процедурами');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Health Retreat'),'ka', 'ჯანმრთელობის დასვენება', 'დაისვენეთ ჩვენს ჯანმრთელობის კურორტზე აღდგენის პროცედურებით');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot, image_url) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Sports Challenge', 'Participate in thrilling sports events and competitions', 450.00, 'SPORTS', 'TRAIN', 'TWO_STARS', 'REGISTERED', DATEADD('DAY', 9,CURRENT_DATE), DATEADD('DAY',18,CURRENT_DATE), (SELECT id FROM users WHERE username='user2'), FALSE, 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&h=675&crop=entropy&q=80');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Sports Challenge'),'en', 'Sports Challenge', 'Participate in thrilling sports events and competitions');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Sports Challenge'),'uz', 'Sport sinovi', 'Qiziqarli sport tadbirlari va musobaqalarda qatnashing');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Sports Challenge'),'ru', 'Спортивный вызов', 'Участвуйте в захватывающих спортивных событиях и соревнованиях');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Sports Challenge'),'ka', 'სპორტული გამოწვევა', 'მიიღეთ მონაწილეობა შთამბეჭდავ სპორტულ ღონისძიებებსა და შეჯიბრებებში');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot, image_url) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Leisure Escape', 'Enjoy a luxurious leisure escape with premium services', 1150.00, 'LEISURE', 'PLANE', 'THREE_STARS', 'PAID', DATEADD('DAY', 4,CURRENT_DATE), DATEADD('DAY',14,CURRENT_DATE), (SELECT id FROM users WHERE username='admin'), TRUE, 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&h=675&crop=entropy&q=80');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Leisure Escape'),'en', 'Leisure Escape', 'Enjoy a luxurious leisure escape with premium services');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Leisure Escape'),'uz', 'Hordiq chiqarish dami', 'Premium xizmatlar bilan hashamatli dam olishdan bahramand bo''ling');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Leisure Escape'),'ru', 'Расслабляющий отдых', 'Насладитесь роскошным отдыхом с премиальными сервисами');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Leisure Escape'),'ka', 'დასვენების გაქცევა', 'ისიამოვნეთ მდიდრული დასვენებით პრემიუმ სერვისებით');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot, image_url) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Wild Safari', 'Experience the wild with guided safari tours on majestic landscapes', 1400.00, 'SAFARI', 'SHIP', 'FOUR_STARS', 'REGISTERED', DATEADD('DAY', 7,CURRENT_DATE), DATEADD('DAY',16,CURRENT_DATE), (SELECT id FROM users WHERE username='manager'), FALSE, 'https://images.unsplash.com/photo-1452570053594-1b985d6ea890?auto=format&fit=crop&w=1200&h=675&crop=entropy&q=80');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Wild Safari'),'en', 'Wild Safari', 'Experience the wild with guided safari tours on majestic landscapes');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Wild Safari'),'uz', 'Yovvoyi safari', 'Yo''riqchi bilan safarilar orqali ulug''vor manzaralarda yovvoyi tabiatni his qiling');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Wild Safari'),'ru', 'Дикое сафари', 'Почувствуйте дикую природу в сопровождении сафари по величественным ландшафтам');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Wild Safari'),'ka', 'ველური საფარი', 'გაიცანით ველური ბუნება გიდიან საფარებთან ერთად დიდებულ ლანდშაფტებზე');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot, image_url) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Wine Tasting Journey', 'Indulge in exquisite wines and gourmet experiences', 1300.00, 'WINE', 'PRIVATE_CAR', 'FIVE_STARS', 'PAID', DATEADD('DAY', 3,CURRENT_DATE), DATEADD('DAY',9,CURRENT_DATE), (SELECT id FROM users WHERE username='support'), TRUE, 'https://images.unsplash.com/photo-1444723121867-7a241cacace9?auto=format&fit=crop&w=1200&h=675&crop=entropy&q=80');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Wine Tasting Journey'),'en', 'Wine Tasting Journey', 'Indulge in exquisite wines and gourmet experiences');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Wine Tasting Journey'),'uz', 'Vino degustatsiyasi sayohati', 'Nafis vinolar va gurme tajribalardan bahramand bo''ling');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Wine Tasting Journey'),'ru', 'Винное путешествие', 'Насладитесь изысканными винами и гастрономическими впечатлениями');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Wine Tasting Journey'),'ka', 'ღვინის დეგუსტაციის მოგზაურობა', 'დააგემოვნეთ დახვეწილი ღვინოები და გურმანული გამოცდილებები');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot, image_url) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Eco Nature Trek', 'Embark on an eco-friendly trek through pristine nature trails', 550.00, 'ECO', 'JEEPS', 'TWO_STARS', 'CANCELED', CURRENT_DATE, DATEADD('DAY',5,CURRENT_DATE), (SELECT id FROM users WHERE username='user1'), FALSE, 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&h=675&crop=entropy&q=80');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Eco Nature Trek'),'en', 'Eco Nature Trek', 'Embark on an eco-friendly trek through pristine nature trails');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Eco Nature Trek'),'uz', 'Eko tabiat treki', 'Beg''ubor tabiat yo''llari bo''ylab eko sayohatga chiqing');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Eco Nature Trek'),'ru', 'Эко-трек по природе', 'Отправляйтесь в эко-поход по первозданным природным тропам');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Eco Nature Trek'),'ka', 'ეკო ბუნების ლაშქრობა', 'გაემართეთ ეკო ლაშქრობაში დაუვიწყარ ბუნებრივ ბილიკებზე');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot, image_url) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Adventure Expedition', 'Join an adventurous expedition to explore remote landscapes', 999.99, 'ADVENTURE', 'MINIBUS', 'THREE_STARS', 'REGISTERED', DATEADD('DAY', 7,CURRENT_DATE), DATEADD('DAY',19,CURRENT_DATE), (SELECT id FROM users WHERE username='manager'), TRUE, 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&h=675&crop=entropy&q=80');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Adventure Expedition'),'en', 'Adventure Expedition', 'Join an adventurous expedition to explore remote landscapes');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Adventure Expedition'),'uz', 'Sarguzasht ekspeditsiyasi', 'Uzoq manzaralarni o''rganish uchun sarguzasht ekspeditsiyasiga qo''shiling');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Adventure Expedition'),'ru', 'Приключенческая экспедиция', 'Присоединяйтесь к экспедиции, чтобы исследовать удалённые ландшафты');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Adventure Expedition'),'ka', 'სათავგადასავლო ექსპედიცია', 'შეუერთდით ექსპედიციას შორეული ლანდშაფტების შესასწავლად');

INSERT INTO vouchers (id, title, description, price, tour_type, transfer_type, hotel_type, status, arrival_date, eviction_date, user_id, is_hot, image_url) VALUES (CAST(random_uuid() AS VARCHAR(36)), 'Cultural Odyssey', 'Explore historic sites and immerse in diverse cultural experiences', 799.99, 'CULTURAL', 'ELECTRICAL_CARS', 'FOUR_STARS', 'PAID', CURRENT_DATE, DATEADD('DAY',7,CURRENT_DATE), (SELECT id FROM users WHERE username='admin'), FALSE, 'https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?auto=format&fit=crop&w=1200&h=675&crop=entropy&q=80');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Cultural Odyssey'),'en', 'Cultural Odyssey', 'Explore historic sites and immerse in diverse cultural experiences');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Cultural Odyssey'),'uz', 'Madaniy odisseya', 'Tarixiy joylarni kashf eting va turli madaniy tajribalarga sho''ng''ing');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Cultural Odyssey'),'ru', 'Культурная одиссея', 'Изучайте исторические места и погружайтесь в разнообразные культурные впечатления');
INSERT INTO voucher_translations (id, voucher_id, locale, title, description) VALUES (CAST(random_uuid() AS VARCHAR(36)), (SELECT id FROM vouchers WHERE title='Cultural Odyssey'),'ka', 'კულტურული ოდისეა', 'შეისწავლეთ ისტორიული ადგილები და ჩაეფლეთ მრავალფეროვან კულტურულ გამოცდილებებში');